[[redirects]]
  force = true
  from = "/pathp"
  status = 200
  to = "https://api.cellmodelpassports.sanger.ac.uk/patients?page[size]=10000"
  headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"